/*
 * Daylight — landing page behaviour.
 *
 * The demo is not a mock-up. It drives the app's real engine (assets/engine.js,
 * a port of Sources/DaylightCore) over the app's real presets and city list
 * (assets/data.js, generated by `Daylight --export-site-data`). Scrubbing the
 * day here produces the values the app would produce.
 */
(() => {
  'use strict';

  // Scripting is available, so anything hidden for its absence can come back.
  document.documentElement.classList.remove('no-js');

  const E = window.DaylightEngine;
  if (!E) return;

  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const DAY = E.DAY;
  const $ = (id) => document.getElementById(id);

  const svg = $('curve');
  if (!svg) return;
  const stage = document.querySelector('.hero-demo');

  // ------------------------------------------------------------- state

  const state = {
    preset: E.presets[0],
    city: null,
    anchors: [],
    minute: nowMinute(),
    following: true,
    comparing: false,
  };

  function nowMinute() { const d = new Date(); return d.getHours() * 60 + d.getMinutes(); }

  function recompute() {
    state.anchors = E.resolveAnchors(state.preset, state.city);
  }

  // ----------------------------------------------------------- presets

  const presetBlurb = {
    'Balanced': 'A moderate shift towards warmer, dimmer evenings.',
    'Subtle': 'Barely noticeable during the day, mildly warm at night.',
    'Extra Warm': 'A pronounced shift, quite warm and dim late on.',
    'Follow the sun': 'Sunrise and sunset where you are, clamped so it stays sensible all year.',
  };

  const presetHolder = document.querySelector('.demo-presets');
  E.presets.forEach((preset, i) => {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'preset-chip' + (i === 0 ? ' is-active' : '');
    b.textContent = preset.name;
    b.setAttribute('role', 'radio');
    b.setAttribute('aria-checked', i === 0 ? 'true' : 'false');
    b.title = presetBlurb[preset.name] || '';
    b.addEventListener('click', () => selectPreset(preset, b));
    // Arrow keys move between presets, as a radio group should.
    b.addEventListener('keydown', (e) => {
      const chips = [...presetHolder.querySelectorAll('.preset-chip')];
      const at = chips.indexOf(b);
      let to = null;
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') to = chips[(at + 1) % chips.length];
      if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') to = chips[(at - 1 + chips.length) % chips.length];
      if (to) { e.preventDefault(); to.click(); to.focus(); }
    });
    presetHolder.appendChild(b);
  });

  function selectPreset(preset, button) {
    state.preset = preset;
    presetHolder.querySelectorAll('.preset-chip').forEach((c) => {
      const on = c === button;
      c.classList.toggle('is-active', on);
      c.setAttribute('aria-checked', on ? 'true' : 'false');
      c.tabIndex = on ? 0 : -1;
    });
    $('demo-title').textContent = `A day on the ${preset.name} schedule`;
    $('demo-sub').textContent = presetBlurb[preset.name] || '';
    document.querySelector('.demo-place').classList.toggle('is-needed', usesSolar(preset) && !state.city);
    recompute();
    draw();
    paint(state.minute);
  }

  const usesSolar = (preset) => preset.anchors.some((a) => a.kind === 'solar');

  // ------------------------------------------------------------ cities

  const citySelect = $('city');
  const byRegion = new Map();
  E.cities.forEach((c) => {
    if (!byRegion.has(c.region)) byRegion.set(c.region, []);
    byRegion.get(c.region).push(c);
  });
  [...byRegion.keys()].sort().forEach((region) => {
    const group = document.createElement('optgroup');
    group.label = region;
    byRegion.get(region).sort((a, b) => a.name.localeCompare(b.name)).forEach((c) => {
      const o = document.createElement('option');
      o.value = `${c.name}|${c.region}`;
      o.textContent = c.name;
      group.appendChild(o);
    });
    citySelect.appendChild(group);
  });

  citySelect.addEventListener('change', () => {
    const [name, region] = citySelect.value.split('|');
    state.city = E.cities.find((c) => c.name === name && c.region === region) || null;
    try {
      if (state.city) localStorage.setItem('daylight.city', citySelect.value);
      else localStorage.removeItem('daylight.city');
    } catch { /* private browsing; the page works without remembering */ }
    document.querySelector('.demo-place').classList.toggle('is-needed', usesSolar(state.preset) && !state.city);
    recompute();
    draw();
    paint(state.minute);
    updateSun();
  });

  /* A starting guess from the visitor's own time zone. A time zone is a
     setting, not a position, so this costs no permission — and it is only ever
     preselected for confirmation, never used to claim we know where they are. */
  function guessCity() {
    try {
      const saved = localStorage.getItem('daylight.city');
      if (saved) {
        const [n, r] = saved.split('|');
        const hit = E.cities.find((c) => c.name === n && c.region === r);
        if (hit) return hit;
      }
    } catch { /* ignore */ }
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    return E.cities.find((c) => c.tz === tz)
        || E.cities.find((c) => c.tz.split('/')[0] === tz.split('/')[0])
        || null;
  }

  /* Today's real sunrise and sunset for the chosen city, computed here rather
     than read off the schedule — they are useful context whichever preset is
     showing, and reading them from the anchors made the city picker look inert
     on the three presets that do not follow the sun. */
  function updateSun() {
    const el = $('sun-readout');
    if (!state.city) { el.textContent = ''; return; }
    const c = state.city;
    const now = new Date();
    const { year, month, day } = E.dateInZone(c.tz, now);
    const offsetMinutes = E.zoneOffsetMinutes(c.tz, now);
    const at = (kind) => E.solarEvent(kind, { year, month, day, lat: c.lat, lon: c.lon, offsetMinutes });
    const rise = at('sunrise'), set = at('sunset');

    if (rise === E.POLAR_DAY || set === E.POLAR_DAY) {
      el.textContent = 'The sun does not set there today';
    } else if (rise === E.POLAR_NIGHT || set === E.POLAR_NIGHT) {
      el.textContent = 'The sun does not rise there today';
    } else {
      el.textContent = `Sun ${E.clockString(rise)} – ${E.clockString(set)}`;
    }
    el.title = `Sunrise and sunset today in ${c.name}, on ${c.name}'s own clock`;
  }

  // ------------------------------------------------------------ drawing

  const NS = 'http://www.w3.org/2000/svg';
  const W = 1000, H = 260, PAD_TOP = 18, PAD_BOTTOM = 34;
  const plotH = H - PAD_TOP - PAD_BOTTOM;
  const x = (minute) => (minute / DAY) * W;
  const y = (kelvin) => {
    const lo = E.mired(E.constants.neutralKelvin), hi = E.mired(E.constants.warmestKelvin);
    return PAD_TOP + Math.min(Math.max((E.mired(kelvin) - lo) / (hi - lo), 0), 1) * plotH;
  };
  const rgba = (c, a) => `rgba(${c[0]}, ${c[1]}, ${c[2]}, ${a})`;

  function draw() {
    while (svg.firstChild) svg.removeChild(svg.firstChild);

    const step = 4;
    const samples = [];
    for (let m = 0; m <= DAY; m += step) samples.push({ m, ...E.evaluate(state.anchors, m) });

    const defs = document.createElementNS(NS, 'defs');
    const grad = document.createElementNS(NS, 'linearGradient');
    grad.setAttribute('id', 'dayFill');
    grad.setAttribute('x1', '0'); grad.setAttribute('x2', '1');
    grad.setAttribute('y1', '0'); grad.setAttribute('y2', '0');
    for (let i = 0; i <= 48; i++) {
      const s = E.evaluate(state.anchors, (i / 48) * DAY);
      const stop = document.createElementNS(NS, 'stop');
      stop.setAttribute('offset', `${(i / 48) * 100}%`);
      stop.setAttribute('stop-color', rgba(E.swatch(s.kelvin), 0.62));
      grad.appendChild(stop);
    }
    defs.appendChild(grad);
    svg.appendChild(defs);

    let d = `M 0 ${H - PAD_BOTTOM}`;
    samples.forEach((s) => { d += ` L ${x(s.m).toFixed(2)} ${y(s.kelvin).toFixed(2)}`; });
    d += ` L ${W} ${H - PAD_BOTTOM} Z`;
    const area = document.createElementNS(NS, 'path');
    area.setAttribute('d', d);
    area.setAttribute('fill', 'url(#dayFill)');
    svg.appendChild(area);

    const line = document.createElementNS(NS, 'path');
    line.setAttribute('d', samples.map((s, i) =>
      `${i ? 'L' : 'M'} ${x(s.m).toFixed(2)} ${y(s.kelvin).toFixed(2)}`).join(' '));
    line.setAttribute('class', 'curve-line');
    svg.appendChild(line);

    for (let h = 0; h <= 24; h += 3) {
      const hx = x(h * 60);
      const tick = document.createElementNS(NS, 'line');
      tick.setAttribute('x1', hx); tick.setAttribute('x2', hx);
      tick.setAttribute('y1', H - PAD_BOTTOM); tick.setAttribute('y2', H - PAD_BOTTOM + 5);
      tick.setAttribute('class', 'curve-tick');
      svg.appendChild(tick);
      if (h % 6 === 0 && h < 24) {
        const label = document.createElementNS(NS, 'text');
        label.setAttribute('x', hx + 6);
        label.setAttribute('y', H - PAD_BOTTOM + 20);
        label.setAttribute('class', 'curve-label');
        label.textContent = h === 0 ? '12 AM' : h === 12 ? 'Noon' : h > 12 ? `${h - 12} PM` : `${h} AM`;
        svg.appendChild(label);
      }
    }

    state.anchors.forEach((a) => {
      const ax = x(a.minute);
      const mark = document.createElementNS(NS, 'line');
      mark.setAttribute('x1', ax); mark.setAttribute('x2', ax);
      mark.setAttribute('y1', PAD_TOP); mark.setAttribute('y2', H - PAD_BOTTOM);
      mark.setAttribute('class', 'curve-anchor' + (a.origin && a.origin.startsWith('clamped') ? ' is-clamped' : ''));
      svg.appendChild(mark);
    });

    const marker = document.createElementNS(NS, 'line');
    marker.setAttribute('id', 'marker');
    marker.setAttribute('y1', PAD_TOP - 8); marker.setAttribute('y2', H - PAD_BOTTOM);
    marker.setAttribute('class', 'curve-marker');
    svg.appendChild(marker);

    const dot = document.createElementNS(NS, 'circle');
    dot.setAttribute('id', 'marker-dot');
    dot.setAttribute('r', '4');
    dot.setAttribute('class', 'curve-marker-dot');
    svg.appendChild(dot);

    setTrackGradient();
    describeCurve(samples);
    drawAnchorList();
  }

  /* The scrubber's track shows the day it scrubs through, so the control is
     also a legend for the chart above it. */
  function setTrackGradient() {
    const stops = [];
    for (let i = 0; i <= 24; i++) {
      const s = E.evaluate(state.anchors, (i / 24) * DAY);
      stops.push(`${rgba(E.swatch(s.kelvin), 1)} ${((i / 24) * 100).toFixed(1)}%`);
    }
    stage.style.setProperty('--day-gradient', `linear-gradient(90deg, ${stops.join(', ')})`);
  }

  /* A text equivalent of the curve, kept in step with it — the shape of the
     day is information, and it should not be available only to people who can
     see the picture. */
  function describeCurve(samples) {
    const warmest = samples.reduce((a, b) => (b.kelvin < a.kelvin ? b : a));
    const coolest = samples.reduce((a, b) => (b.kelvin > a.kelvin ? b : a));
    $('curve-desc').textContent =
      `A 24-hour curve of display warmth for the ${state.preset.name} schedule` +
      (state.city ? ` in ${state.city.name}` : '') +
      `. Coolest at ${E.clockString(coolest.m)}, about ${Math.round(coolest.kelvin / 50) * 50} kelvin. ` +
      `Warmest at ${E.clockString(warmest.m)}, about ${Math.round(warmest.kelvin / 50) * 50} kelvin. ` +
      `Steps: ${state.anchors.map((a) => `${a.name} at ${E.clockString(a.minute)}`).join(', ')}.`;
  }

  function drawAnchorList() {
    const list = $('anchor-list');
    list.innerHTML = '';
    state.anchors.forEach((a) => {
      const li = document.createElement('li');
      const note = a.origin === 'clamped-early' ? 'held later than sunset'
                 : a.origin === 'clamped-late' ? 'held earlier than sunset'
                 : a.origin === 'no-location' ? 'fallback — no city chosen'
                 : a.origin === E.POLAR_DAY ? 'the sun does not set today'
                 : a.origin === E.POLAR_NIGHT ? 'the sun does not rise today'
                 : a.kind === 'solar' ? 'follows the sun' : '';
      li.innerHTML =
        `<span class="a-time">${E.clockString(a.minute)}</span>` +
        `<span class="a-name">${a.name}</span>` +
        `<span class="a-val">${Math.round(a.kelvin / 50) * 50} K · ${Math.round(a.brightness * 100)}%</span>` +
        (note ? `<span class="a-note">${note}</span>` : '');
      list.appendChild(li);
    });
  }

  // ------------------------------------------------------------ painting

  const slider = $('scrub');
  const nowButton = $('scrub-now');
  const tint = $('preview-tint');

  function paint(minute) {
    const s = E.evaluate(state.anchors, minute);
    const px = x(minute);
    const marker = $('marker'), dot = $('marker-dot');
    if (marker) { marker.setAttribute('x1', px); marker.setAttribute('x2', px); }
    if (dot) { dot.setAttribute('cx', px); dot.setAttribute('cy', y(s.kelvin)); }

    const k = Math.round(s.kelvin / 50) * 50;
    const pct = Math.round(s.brightness * 100);
    $('read-time').textContent = E.clockString(minute);
    $('read-name').textContent = s.name;
    $('read-kelvin').textContent = `${k} K`;
    $('read-brightness').textContent = `${pct}%`;

    const c = E.swatch(s.kelvin);
    stage.style.setProperty('--moment', rgba(c, 1));
    stage.style.setProperty('--moment-soft', rgba(c, 0.13));
    stage.style.setProperty('--moment-faint', rgba(c, 0.05));

    /* The preview multiplies the sample by the very gains the app writes to the
       display, so the simulation is the same arithmetic — applied to one box on
       a web page rather than to the screen. */
    if (state.comparing) {
      tint.style.backgroundColor = 'rgb(255, 255, 255)';
    } else {
      const g = E.channelGains(s.kelvin);
      const d = s.brightness;
      tint.style.backgroundColor =
        `rgb(${Math.round(255 * g[0] * d)}, ${Math.round(255 * g[1] * d)}, ${Math.round(255 * g[2] * d)})`;
    }

    slider.setAttribute('aria-valuetext',
      `${E.clockString(minute)}, ${s.name}, about ${k} kelvin, ${pct} percent brightness`);
  }

  function setMinute(minute, userDriven) {
    state.minute = minute;
    if (userDriven) { state.following = false; nowButton.hidden = false; }
    slider.value = String(Math.round(minute));
    paint(minute);
  }

  slider.addEventListener('input', () => setMinute(Number(slider.value), true));
  nowButton.addEventListener('click', () => {
    state.following = true;
    nowButton.hidden = true;
    setMinute(nowMinute(), false);
    slider.focus();
  });

  // Hold to see the display untouched, which is the comparison that matters.
  const compare = $('compare');
  const setCompare = (on) => {
    state.comparing = on;
    compare.setAttribute('aria-pressed', on ? 'true' : 'false');
    compare.classList.toggle('is-on', on);
    paint(state.minute);
  };
  ['mousedown', 'touchstart'].forEach((ev) =>
    compare.addEventListener(ev, (e) => { e.preventDefault(); setCompare(true); }, { passive: false }));
  ['mouseup', 'mouseleave', 'touchend', 'touchcancel', 'blur'].forEach((ev) =>
    compare.addEventListener(ev, () => setCompare(false)));
  compare.addEventListener('keydown', (e) => {
    if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); setCompare(!state.comparing); }
  });

  // ------------------------------------------------------------ start up

  state.city = guessCity();
  if (state.city) citySelect.value = `${state.city.name}|${state.city.region}`;
  recompute();
  draw();
  setMinute(nowMinute(), false);
  nowButton.hidden = true;
  updateSun();
  presetHolder.querySelectorAll('.preset-chip').forEach((c, i) => { c.tabIndex = i === 0 ? 0 : -1; });

  // Keep following the clock until the visitor takes over. Anchors are
  // recomputed too, so a solar schedule stays right across midnight.
  setInterval(() => {
    if (!state.following) return;
    recompute();
    draw();
    setMinute(nowMinute(), false);
    updateSun();
  }, 60000);

  // ------------------------------------------------------------ page bits

  const revealables = document.querySelectorAll('[data-reveal]');
  const showAll = () => revealables.forEach((el) => el.classList.add('is-visible'));

  if (!reduceMotion && 'IntersectionObserver' in window && revealables.length) {
    document.documentElement.classList.add('js-reveal');
    const io = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (e.isIntersecting) { e.target.classList.add('is-visible'); io.unobserve(e.target); }
      });
    }, { rootMargin: '0px 0px -12% 0px' });
    revealables.forEach((el) => io.observe(el));
    setTimeout(showAll, 3000);
    document.addEventListener('visibilitychange', () => {
      if (!document.hidden) setTimeout(showAll, 400);
    });
  } else {
    showAll();
  }

  document.querySelectorAll('[data-copy]').forEach((button) => {
    button.addEventListener('click', async () => {
      const text = document.getElementById(button.dataset.copy)?.textContent?.trim();
      if (!text) return;
      try {
        await navigator.clipboard.writeText(text);
        const previous = button.textContent;
        button.textContent = 'Copied';
        button.classList.add('is-done');
        setTimeout(() => { button.textContent = previous; button.classList.remove('is-done'); }, 1600);
      } catch { button.textContent = 'Press ⌘C'; }
    });
  });

  const isMac = /Mac|iPhone|iPad/.test(navigator.platform) || /Mac OS X/.test(navigator.userAgent);
  if (!isMac) document.querySelectorAll('[data-mac-only]').forEach((el) => { el.hidden = false; });

  $('year').textContent = String(new Date().getFullYear());
})();
